### PR TITLE
add stub for HLA nomenclature terminology upload

### PR DESCRIPTION
**Pull request by jschneid-nmdp**
This is an initial step toward adding support for upload of HLA nomenclature via the $upload-external-code-system operation.

Currently seeking comments and feedback, or, if this looks like a reasonable start, would welcome having it merged into the main hapi-fhir repo.

### CODE REVIEW

**Comment by jamesagnew** [comment]
HI @jschneid-nmdp - This is great, looks awesome!

My only one request: Would you be able to add a simple test along the lines of the [LOINC One](https://github.com/jamesagnew/hapi-fhir/blob/master/hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/term/TerminologyLoaderSvcLoincTest.java). It doesn't need to be fancy, but having a test like this will ensure that any future changes to the framework don't break your work.

**Comment by jschneid-nmdp** [comment]
I've added a very basic TerminologyLoaderSvcImgthlaTest, patterned after TerminologyLoaderSvcLoincTest, and made some related minor modifications to the TerminologyLoaderSvcImpl.processImgthlaFiles method (to allow for files located in subdirectories of the zipfile).

**Comment by jamesagnew** [comment]
Fantastic, thanks! Will merge now.

**Comment by jschneid-nmdp** [comment]
Thanks!

**Pull request merged**
