### PR TITLE
Implement #826 - add OSGI support and Apache Karaf features with inte…

### PR DESCRIPTION
**Pull request by johnpoth**
…gration tests

This PR is part of #826 which adds OSGI support and Apache Karaf features for the HAPI-FHIR project.

This PR adds OSGI support for:

- [X]  HAPI-FHIR structures DSTU2, HL7ORGDSTU2, DSTU2.1, DSTU3, R4
- [X]  HAPI-FHIR Resource validation DSTU2, HL7ORGDSTU2, DSTU2.1, DSTU3, R4
- [X]  Apache Karaf features for all the above
- [X]  Integration Tests

What remains to do is:

- [ ] HAPI-FHIR Server support
- [ ] HAPI-FHIR narrative support. This might be tricky as Thymeleaf doesn't support OSGi.
- [ ] Any other features that I've missed :)

Thanks!

### CODE REVIEW

**Comment by johnpoth** [comment]
@jamesagnew bump :)

**Comment by splatch** [comment]
@johnpoth hey, this PR is quite interesting for me as I am Karaf commiter and I work with HAPI these days. I will be able to test it with my OSGi based deployment which is (luckily) free of Hibernate.

**Comment by jamesagnew** [comment]
Very cool, looks great! I'm going to merge this now. 

One note, I'm going to move the new modules into a directory called `osgi` because the repo is getting massive and I'm trying to organize it a bit. Hopefully that doesn't cause any issues.

**Comment by jamesagnew** [comment]
@johnpoth [This file](https://github.com/johnpoth/hapi-fhir/blob/2c65a6dda72f85e47d54fb397512d7ed01665d05/hapi-fhir-karaf-integration-tests/src/test/java/ca/uhn/fhir/tests/integration/karaf/client/FhirClientTest.java) has a classname that doesn't match the file name. I had to delete it to get the build to pass. Would you mind to have a look?

**Comment by splatch** [comment]
Hey James,
I been on it and fixed compile error locally. Feel free to pull deleted file from #905.

Cheers,
Lukasz

**Comment by johnpoth** [comment]
Thanks @jamesagnew for merging! Looks like I didn't run 'git add' on some changes on my last commit.

#906 updates that, @splatch  please update as well.

Thanks!

**Comment by anthonys123** [comment]
Hi John/Lukasz - I'm trying to debug the latest 3.4.0 master version of the JPA Server in IntelliJ Ultimate and am encountering some OSGi-related build errors shown in the screenshot below.  A Maven build from the Command Prompt works fine.  Would you have any ideas what is happening here?  

ArrayIndexOutOfBoundsExceptions being thrown by the DSAnnotations and MetatypeAnnotations plug-ins.  Is **bnd** being used for the OSGi packaging?

untitled

**Comment by splatch** [comment]
@anthonys123 - just remove OSGI facet from project and you will be fine.

**Comment by anthonys123** [comment]
Many thanks Lukasz for the quick reply.  That fixed it.

**Comment by anthonys123** [comment]
Lukasz - I'm curious, is this an interaction issue between IntelliJ and the OSGi framework?  Should I log an issue about this?

**Comment by splatch** [comment]
It's IDE error at this stage. You don't run OSGi framework at this point but your developer tool attempts to warn you about things which could happen in runtime by enforcing some checks while you work.
Main problem is that IntelliJ doesn't really support manifests generated from maven plugin. That's why it tends to fail big time on every project which does not follow their way.

**Comment by anthonys123** [comment]
Understood - thanks for the clarification.

**Pull request merged**
