### PR TITLE
Preserve contained resource meta when encoding to dao

### PR DESCRIPTION
**Pull request by basecade**
The contained resource meta data is not persisted when saving parent resource to database. When persisting resource to database the following setting is used on the database:
parser.setDontEncodeElements(ResourceMetaParams.EXCLUDE_ELEMENTS_IN_ENCODED);

This is okay for the parent resource beause the meta data is saved somewhere else, but for the contained resource the meta is just lost when not persisting.

Test to reproduce problem: https://groups.google.com/forum/#!topic/hapi-fhir/uxVxxldqsBI

### CODE REVIEW

**Comment by jamesagnew** [comment]
Hi @basecade ,

Thanks for the PR! This is neat.

Can I ask you to include unit tests that demonstrate and test the functionality being added?

**Comment by patrick-werner** [comment]
Hi @basecade,

did you pay respect to these constrains of the FHIR spec?
> Contained resources SHALL NOT contain meta.versionId, meta.lastUpdated, or meta.security.

**Comment by basecade** [comment]
Hi James,

I have actually written a test but was not sure where to place it:

public void encodeResourceToString_withEXCLUDE_ELEMENTS_IN_ENCODED_metaKeptInContainedResource() {
        // Arrange
        Organization containedOrganization = new Organization();
        containedOrganization.getMeta().addProfile("http://organization.custom");

        Patient patient = new Patient();
        patient.setId(UUID.randomUUID().toString());
        patient.getMeta().addProfile("http://hl7.org/fhir/StructureDefinition/Patient");
        patient.setGeneralPractitioner(Arrays.asList(new Reference(containedOrganization)));

        IParser parser = ResourceEncodingEnum.JSONC.newParser(new DummyFhirContext());
        parser.setDontEncodeElements(ResourceMetaParams.EXCLUDE_ELEMENTS_IN_ENCODED);

        // Act
        String encodedPatient = parser.encodeResourceToString(patient);

        // Assert
        assertThat(encodedPatient).contains("\"meta\":{\"profile\":[\"http://organization.custom\"]}");
        assertThat(StringUtils.countMatches(encodedPatient, "\"meta\"")).isEqualTo(1);
    }

Did you have another test in mind?

Best Regards,
Anders Havn

**Comment by basecade** [comment]
> Contained resources SHALL NOT contain meta.versionId, meta.lastUpdated, or meta.security

Hi Patrick,

I did not know that. Is it the Hapi framework that should enforce this or the user of the framework?

Best Regards,
Anders Havn

**Comment by jamesagnew** [comment]
@basecade One of the JsonParserXXXTest or XmlParserXXXTest classes would be a good home for tests for this new functionality.

And to @patrick-werner 's point, it would be good to have tests that confirm that the FHIR rules he mentioned are still being respected.

**Comment by basecade** [comment]
I have now tried to update the code and added a test.

**Comment by jamesagnew** [comment]
Nice work, this looks like it fits the bill. 👍

**Pull request merged**
