### PR TITLE
Some work on jamesagnew/hapi-fhir/#1297

### PR DESCRIPTION
**Pull request by jelmerterwal**

### CODE REVIEW

**Comment by jamesagnew** [comment]
Hi @jelmerterwal - Would you be able to provide some details about the issue that this PR addresses?

**Comment by jelmerterwal** [comment]
Hi @jamesagnew - This is an initial attempt to fix https://github.com/jamesagnew/hapi-fhir/issues/1297. The example in that issue shows that it is not always possible to use equivalent Kotlin code in cases Java code would have worked.

**Comment by jamesagnew** [comment]
@jelmerterwal ah, got it.

Looks like this change is breaking CI so it probably needs some work unfortunately. Do you think it would be realistic to include a Kotlin integration test in the main HAPI build so as to provide some kind of test coverage for these changes? I'm picturing a module like `hapi-fhir-server-kotlin-test` that reproduces the type of setup that is in the ticket you linked.

**Comment by jelmerterwal** [comment]
@jamesagnew okay, think I see why I broke it. Hopefully this will fix the build and will add a test later today or tomorrow

**Comment by jelmerterwal** [comment]
@jamesagnew can you have a look?

Notes;
- we (my colleague and I) removed some overrides since these blocked a working build, tests still work
- we fixed a problem with `CodeableConcept` as well

**Comment by jamesagnew** [comment]
This is looking cool! Why did you scrap the `hapi-fhir-server-kotlin-test` though? I don't know about overloading hapi-fhir-jaxrsserver-example into being both a demo of the alternate JAX-RS server functionality and Kotlin support.. JAX-RS is not well supported as it is, and I'm worried that adding Kotlin into the mix there will further confuse people who are trying to use it as an example.

**Comment by jelmerterwal** [comment]
I see, separated the example from the Kotlin test.

**Comment by jamesagnew** [comment]
Looks great, I've merged it. Thanks for the PR!

**Pull request merged**
