### PR TITLE
Ensure that older DSTU3 versions use the legacy mime types

### PR DESCRIPTION
**Pull request by lawley**
For dstu3 structures corresponding to FHIR version 1.4.0 (eg the Baltimore / May2016 snapshot), ensure that the legacy mime types are used instead of the newer ones.

### CODE REVIEW

**Comment by jamesagnew** [comment]
Thanks for the PR. I've merged it!

I'm going to check in a little modification to this, basically moving the version string that's pulled from the model out of RestulServerUtils and pulling it right up into the FhirDstu3 class. That should preserve your fix, and have the additional benefit that clients and servers will correctly report "1.4.0" if you're using that structures JAR.

Please feel free to re-open this if the fix doesn't work for you.

**Comment by lawley** [comment]
Hi James, sadly the introduction of a new method in the structures library won't work for our case because we are tied to an old version of the structures library (b8f1f39ead1a8e8f09f2491159b45f26609ad256) and thus we need a patch that doesn't change hapi-fhir-structures-dstu3 but only hapi-fhir-base.

Otherwise we get:

```
java.lang.AbstractMethodError: org.hl7.fhir.dstu3.hapi.ctx.FhirDstu3.getVersionString()Ljava/lang/String;
	at ca.uhn.fhir.rest.client.api.HttpClientUtil.createUserAgentString(HttpClientUtil.java:33)
	at ca.uhn.fhir.rest.client.apache.ApacheHttpClient.addHeadersToRequest(ApacheHttpClient.java:143)
	at ca.uhn.fhir.rest.client.apache.ApacheHttpClient.createGetRequest(ApacheHttpClient.java:132)
	at ca.uhn.fhir.rest.client.BaseHttpClientInvocation.createHttpRequest(BaseHttpClientInvocation.java:77)
	at ca.uhn.fhir.rest.method.HttpGetClientInvocation.asHttpRequest(HttpGetClientInvocation.java:112)
	at ca.uhn.fhir.rest.client.BaseClient.invokeClient(BaseClient.java:226)
	at ca.uhn.fhir.rest.client.GenericClient$BaseClientExecutable.invoke(GenericClient.java:637)
	at ca.uhn.fhir.rest.client.GenericClient$FetchConformanceInternal.execute(GenericClient.java:929)
	at ca.uhn.fhir.rest.client.RestfulClientFactory.validateServerBase(RestfulClientFactory.java:302)
	at ca.uhn.fhir.rest.client.RestfulClientFactory.validateServerBaseIfConfiguredToDoSo(RestfulClientFactory.java:203)
	at ca.uhn.fhir.rest.client.BaseClient.invokeClient(BaseClient.java:189)
	at ca.uhn.fhir.rest.client.BaseClient.fetchResourceFromUrl(BaseClient.java:121)
```

**Comment by jamesagnew** [comment]
Aw nuts.

I'm assuming you're looking for support for FHIR 1.4.0 (Montreal snapshot)?

I've actually just added a new `hapi-fhir-structures-dstu2.1` module which should bring stable support for that version. Would this be an option for you?

Either way, I'm sure we can find a way to get this working without changing the signature of IFhirVersion then

**Comment by jamesagnew** [comment]
...and now the current method should work too.

**Comment by lawley** [comment]
Yes, FHIR 1.4.0 May 2016 (Montreal) is the one.

I've just updated our code to use the new dstu2.1 structures and it looks good!

**Pull request merged**
