### PR TITLE
[(master)] Added support for extensions in Meta resource

### PR DESCRIPTION
**Pull request by sjanic**
A fix for issue: #772 

Known limitations:
-  If you add an extension to a resource's Meta, you have to make the url used as key unique. When we deserialize the meta resource back we use the extension url as key, and duplicate keys will be ignored.

- In my own organisation we only use the Json part of Hapi Fhir, so I haven't added Xml support given other priorities. If I have the time, or somebody else wants to, feel free to add it.

~~- Subextensions are not supported in extensions that are located in Meta.~~

### CODE REVIEW

**Comment by sjanic** [comment]
Hmm... It seemed when I cloned the branch and made my changes, DeviceStatus and DeviceStatusEnumFactory got changed. I didn't intent to do that, as my fix doesn't involve these two files, so I assume the files got auto generated when running mvn install.

I have reverted the files, but it seems that the class names differs from the file names. Class Devicestatus is has file name DeviceStatus.java and DevicestatusEnumFactory has file name DeviceStatusEnumFactory. According to Java file name and class name should be the same. 
@jamesagnew Is this as expected?

**Comment by sjanic** [comment]
Can see that build server gave me the following error in the tests:
```
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 11.373 s <<< FAILURE! - in ca.uhn.fhir.jpa.subscription.RestHookTestDstu3Test
[ERROR] testRestHookSubscriptionApplicationXml(ca.uhn.fhir.jpa.subscription.RestHookTestDstu3Test)  Time elapsed: 4.164 s  <<< ERROR!
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: HTTP 500 Server Error: Failed to call access method
	at ca.uhn.fhir.jpa.subscription.RestHookTestDstu3Test.testRestHookSubscriptionApplicationXml(RestHookTestDstu3Test.java:238)
```

I can see that it is a server error, but I wasn't able to reproduce it on my local machine. It is possible to get some log files from the build servers?

**Comment by sjanic** [comment]
I have looked at the changes again, and it seems that extensions on meta can reuse some of the logic that is used for encoding extensions on resources.
It allows me to remove the limitation of not having sub-extensions in meta.

I need to clean up the code, and I'll post it to my fork when that is done.

**Comment by jamesagnew** [comment]
Thanks for the PR! It has been merged. Please send me a note if you'd like your real name to appear in the contributors section of our website!

**Pull request merged**
