### PR TITLE
Full resource/composite Tinder model with generic templates

### PR DESCRIPTION
**Pull request by bdenton**
This PR enhances the generic single and multi-file Maven plugin and the Ant task as follows:

1) Provides the full Tinder data model with composites, valuesets, and profiles
2) Supports generating files for resources, composites, valuesets, and profiles
3) Supports Velocimacro files outside the tinder-plugin JAR
4) Provides filename prefix as well as suffix properties
5) Miscellaneous functional/naming alignment between all three functions

Still to be done in future work: provide full/proper STU3 support in Tinder

### CODE REVIEW

**Comment by jamesagnew** [comment]
This is **super cool**. Wow!

I'm guessing you're still polishing it off? I'm definitely good to merge this whenever you think it's ready.

**Comment by jamesagnew** [comment]
... I'm also totally curious what you're using it for ;)

**Comment by bdenton** [comment]
This has been an interesting exercise. At present, I am using Tinder to generate mapping templates for a new version of our resource mapping engine. So, these changes filled five gaps in that process:

1. The old generic tasks didn't build out the full out the full resource data model. The composites, value sets, and profiles ere never parsed into the model
2. I needed the ability to run templates for composites as well as resources
3. I needed the ability to have my own Velicimacro library files
4. I needed to specify some other Velocity config parameters.. specifically enabling the "macro scope" co I could safely use macros recursively
4. I needed to be able to drill down into the referenced children for a `ResourceBlockCopy`

So, I now have a pretty ugly (but working) set of Velocity code that generates something like the following for resources and composites. This is what I am calling "Annotated JSON" and is used in our mapping engine to produce a JSON structure that matches the template structure. Then this is fed into the changes I made to the JSON parser to produce the Resource. Here is what `Bundle` looks like.. Note the tricky part with the Link block... (The Section block in Composition took some extra care to handle the reference cycle)
```
// /////////////////////////////////////////////////////////
// ////////    Resource: Bundle
// /////////////////////////////////////////////////////////
{
    "Map:Bundle" : version(Dstu2) {
        "resourceType" : "Bundle",
        
    // Resource superclass
    
        "id" : source(?)
            type(IdDt) primitive(String),
        "meta" : source(?)
            typeref(MetaDt),
        "implicitRules" : source(?)
            type(UriDt) primitive(String),
        "language" : source(?)
            typeref(CodeDt),
        
    // DomainResource superclass
    
        "text" : source(?)
            typeref(NarrativeDt),
        "contained" : source(?) 
            [ mapref(*) ],
        "extension" : source(?) 
             [ typeref(ExtensionDt) ],
        "modifierExtension" : source(?) 
            [ typeref(ExtensionDt) ],

    // Child elements
    
        "type" : source(?)
            required
            bindinguri(http://hl7.org/fhir/ValueSet/bundle-type)
            bindingenum(BundleTypeEnum)
            type(BoundCodeDt) primitive(String),
        "total" : source(?)
            type(UnsignedIntDt) primitive(Integer),
        "link" : source(?)
            [ block(Link) {
                "relation" : source(?)
                    required
                    type(StringDt) primitive(String),
                "url" : source(?)
                    required
                    type(UriDt) primitive(String)
            } ],
        "entry" : source(?)
            [ block(Entry) {
                "link" : source(?)
                    [ blockref(Link) {
                        "relation" : source(?)
                            required
                            type(StringDt) primitive(String),
                        "url" : source(?)
                            required
                            type(UriDt) primitive(String)
                    } ],
                "fullUrl" : source(?)
                    type(UriDt) primitive(String),
                "resource" : source(?)
                    typeref(IResource),
                "search" : source(?)
                    block(EntrySearch) {
                        "mode" : source(?)
                            bindinguri(http://hl7.org/fhir/ValueSet/search-entry-mode)
                            bindingenum(SearchEntryModeEnum)
                            type(BoundCodeDt) primitive(String),
                        "score" : source(?)
                            type(DecimalDt) primitive(BigDecimal)
                    },
                "request" : source(?)
                    block(EntryRequest) {
                        "method" : source(?)
                            required
                            bindinguri(http://hl7.org/fhir/ValueSet/http-verb)
                            bindingenum(HTTPVerbEnum)
                            type(BoundCodeDt) primitive(String),
                        "url" : source(?)
                            required
                            type(UriDt) primitive(String),
                        "ifNoneMatch" : source(?)
                            type(StringDt) primitive(String),
                        "ifModifiedSince" : source(?)
                            type(InstantDt) primitive(Date),
                        "ifMatch" : source(?)
                            type(StringDt) primitive(String),
                        "ifNoneExist" : source(?)
                            type(StringDt) primitive(String)
                    },
                "response" : source(?)
                    block(EntryResponse) {
                        "status" : source(?)
                            required
                            type(StringDt) primitive(String),
                        "location" : source(?)
                            type(UriDt) primitive(String),
                        "etag" : source(?)
                            type(StringDt) primitive(String),
                        "lastModified" : source(?)
                            type(InstantDt) primitive(Date)
                    }
            } ],
        "signature" : source(?)
            typeref(SignatureDt)

    }

}
```

**Comment by jamesagnew** [comment]
One last thing.. Can you update `src/changes/changes.xml` with a description? :)

**Pull request merged**
