### PR TITLE
Bd 20200124 mongodb bson parser

### PR DESCRIPTION
**Pull request by bdenton**
First version of ability to parse and encode BSON documents. Includes the Json-Like classes for BSON, a BSON Codec, and small refactorings of the core Json-like interfaces.

### CODE REVIEW

**Comment by jamesagnew** [comment]
This is super cool Bill!

FYI I'm working on getting 4.2.0 out the door this weekend (have been sick this week) but plan on reviewing this as soon as that's happened.

**Comment by bdenton** [comment]
James..
Excellent! I will leave it to you to merge when you think it appropriate. I did want to point out that I have not yet incorporated any of the MongoDB stuff into the master pom build structure. My plan was to have a parent mongodb pom that would build this small first piece along with a more substantial MongoDB server.. maybe somewhat more closely tied to some OSGi framework... maybe looking at existing Karaf stuff but that doesn't look like it has been touched for a while.
cheers, Bill

**Comment by bdenton** [comment]
This PR is no longer compatible with the changes being made in the Jackson parser. I am closing the PR for now

**Comment by jamesagnew** [comment]
Hmm, that's unfortunate.. I wouldn't have expected the Bson parser to have any dependencies on Gson. Ah well.

I wonder if it makes sense to just explore using this library with Jackson once we're done merging the Jackson stuff:

https://github.com/michel-kraemer/bson4jackson

**Pull request closed without merging**
