### PR TITLE
Fixing invalid dom-3 schematron validation for FHIR R4

### PR DESCRIPTION
**Pull request by laurentenhoor**
Based on the discussion with Lloyd McKenzie (https://github.com/lmckenzi) on Stackoverflow (https://stackoverflow.com/a/57761249/10624364), the invalid dom-3 schematron validaton has been corrected for the R4 library.

We filed this in a change proposal at FHIR: https://jira.hl7.org/browse/FHIR-27916

### CODE REVIEW

**Comment by jamesagnew** [comment]
These files are generated, so I'm hesitant to accept pull requests on them because the changes will just get wiped out the next time we generate.

Do you know if this change was applied to the schematrons available for download from hl7.org/fhir ?

**Comment by laurentenhoor** [comment]
Not yet, they are planning to update it.
--
Lauren ten Hoor
+31 6 11865500 <+31611865500>


Op vr 3 jul. 2020 om 13:50 schreef James Agnew <notifications@github.com>:

**Comment by laurentenhoor** [comment]
We filed it here at FHIR: https://jira.hl7.org/browse/FHIR-27916
--
Lauren ten Hoor
+31 6 11865500 <+31611865500>


Op vr 3 jul. 2020 om 13:51 schreef Lauren ten Hoor <laurentenhoor@gmail.com

**Comment by jamesagnew** [comment]
Sounds good- I don't think we can merge this at this time, as HAPI FHIR is the reference Java implementation and as such it needs to match the published version of FHIR.

Once the JIRA ticket gets approved, that's probably the right time for this PR. If you could comment on this PR once that has happened we can absolutely reopen and merge.

**Pull request closed without merging**
