### PR TITLE
extracting request path generating code to protected method in order to ...

### PR DESCRIPTION
**Pull request by harsha89**
...users to have their own mapping to FHIR HAPI rest server  #85

### CODE REVIEW

**Comment by jamesagnew** [comment]
[Jenkins Automated Message] Should I test this patch?

**Comment by harsha89** [comment]
yep sure!

**Comment by jamesagnew** [comment]
Merging this now. Thanks for the contribution!

**Comment by surangak** [comment]
Thanks @jamesagnew  and @harsha89. One step closer to solving FHIR for OpenMRS :-)

**Pull request merged**
