### PR TITLE
Use the charset from the content-type of the HttpEntity instead of always using the default charset.

### PR DESCRIPTION
**Pull request by gijsbert802**
We ran into a character encoding issue on a system where the default charset was not UTF-8. I believe this change fixes our issue.

### CODE REVIEW

**Comment by jamesagnew** [comment]
Hi @gijsbert802 , thanks for the PR!

Is that CI build failure related to the change, or was that happening before you started your changes?

**Comment by gijsbert802** [comment]
The CI build test failure is caused by this change, I'll push a fix.

**Comment by gijsbert802** [comment]
I'm closing the PR for now, the getRequestBodyFromStream method that I "fixed" is only used for logging request bodies, so it will never have a Content-Type header (and cannot be the cause of the issue I had).
I'll do some more debugging.

**Comment by jamesagnew** [comment]
To be honest this seems like a worthwhile change to me.. It may not be the source of the issue you're trying to fix, but if you added a test for null to handle the times when there was no encoding in the response I'd love to merge it. :)

**Comment by gijsbert802** [comment]
Well, yes I agree, but the change was still not good :)
I tested it and it doesn't work because HttpEntity doesn't have content-type set. But there is a header in the request, I'm working on a new PR.

**Pull request closed without merging**
