### PR TITLE
Fixes for issue #1048.  FhirInstanceValidator::validate() now looking…

### PR DESCRIPTION
**Pull request by anthonys123**
… in meta/profile section of request prior to calling InstanceValidator::validate().

### CODE REVIEW

**Comment by anthonys123** [comment]
Hi James - I just realized that there are two more FhirInstanceValidator.java files I need to commit these changes to also.  I'll do that now and create another pull request.

**Comment by jamesagnew** [comment]
Hi Anthony,

After merging this in, we had a few complaints that the new requirement for SD URLs to contain the string StructureDefinition was breaking existing working code. I have rolled this back. Any objections?

**Comment by anthonys123** [comment]
No objections.  Thanks for inquiring.

**Comment by anthonys123** [comment]
Hi James - quick follow-up question (also e-mailed you).  Did you mean that you rolled the entire implementation for this issue out or only the code block that looks for the "StructureDefinition" text?  I interpreted your comment to mean the latter - was that correct?

**Pull request merged**
