### PR TITLE
Elasticsearch mapping for Jpa Server

### PR DESCRIPTION
**Pull request by JiajingLiang**
This PR provides an implementation of ElasticSearch analysis definition for Fhir Jpa Server.

### CODE REVIEW

**Comment by jamesagnew** [comment]
Hi @JiajingLiang - This is looking cool!

Should I wait for an example project before merging or are you planning that in a separate PR?

**Comment by JiajingLiang** [comment]
Hi @jamesagnew, I'm working on the demo application and it's coming in several days. Please wait a little, otherwise people won't know how to use the integration with ElasticSearch. Thanks a lot.

**Comment by JiajingLiang** [comment]
Hello @jamesagnew, 
I added an example configuration class for the ElasticSearch integration, and a mini tutorial paragraph in ReadMe for explaining how to use it.

**Comment by storni** [comment]
Hi @JiajingLiang, thanks for the instructions. Just a minor detail: in Hibernate 5.8.2.Final, the property name for ES analyzers is "hibernate.search.elasticsearch.analysis_definition_provider"  ("analysis" instead of "analyzer")

See [latest hibernate search docs](https://github.com/hibernate/hibernate-search/blob/master/documentation/src/main/asciidoc/elasticsearch-integration.asciidoc)

Regards.

**Comment by JiajingLiang** [comment]
Hi @storni,
Thank you very much for the comment. I've also notice. But as the demo project use the Hibernate 5.7.1.Final, I use the property `hibernate.search.elasticsearch.analyzer_definition_provider`. Of course, if you use the Hibernate 5.8.2.Final, you should use property `hibernate.search.elasticsearch.analysis_definition_provider`

**Comment by jamesagnew** [comment]
Super cool, merging now.

**Comment by jamesagnew** [comment]
Hi @JiajingLiang , I have replaced the `hibernate.search.elasticsearch.analysis_definition_provider` with a constant in order to hoipefully make it easier to catch the change when we upgrade hibernate search.

I have two questions:

1. Are you interested in joining the project to continue maintaining this module on an ongoing basis?
2. What could be done in the way of automated tests for this module? Is it possible to create an integration test that spawns an embedded ES instance to work against?

**Pull request merged**
