### PR TITLE
Changes/fixes and associated unit tests for following _filter operators for strings...

### PR DESCRIPTION
**Pull request by anthonys123**
- eq
- ne
- co
- sw
- ew

### CODE REVIEW

**Comment by anthonys123** [comment]
Hi James - I don't think my changes in this PR triggered the three test failures flagged above.  Their respective stack traces don't show entry into the functions that I modified.

**Comment by anthonys123** [comment]
Hi James - I'll recreate my fork and re-implement the changes for this PR to see if the test errors are resolved.

**Comment by jamesagnew** [comment]
Might be worth holding- I'm in the middle of preparing the 4.1.0 release so
I haven't had a chance to look. If the failures are unrelated I'll comment
on that tomorrow.

**Comment by anthonys123** [comment]
I noticed that I was missing some of the changes you made to SearchBuilder in the most recent commit in my fork.  I've merged your changes into mine and will re-push.  Fingers crossed.

**Comment by anthonys123** [comment]
Hi James - down to one unit test error on this one.  All unit tests for string and date types now pushed.

**Comment by anthonys123** [comment]
Hi James - I've pushed all of my changes for this PR.  The SearchBuilder.java conflict wasn't present when I did the last push.  If you need help with the conflict resolution, let me know.

**Pull request merged**
