### PR TITLE
Fix gettimezone performanceissue

### PR DESCRIPTION
**Pull request by abrsystematic**
TimeZone.getTimeZone() is static synchronized and can take significant time for "custom" time zone ids like "GMT+01:00" - see CustomID on https://docs.oracle.com/javase/7/docs/api/java/util/TimeZone.html. This means that it is a performance bottleneck on systems with high number of transactions. Fixed such that TimeZone is cached in BaseDateTimeDt.

### CODE REVIEW

**Comment by abrsystematic** [comment]
The CustomID format is parsed via java.util.TimeZone#parseCustomTimeZone where the result is not chached by TimeZone.getTimeZone()

**Comment by abrsystematic** [comment]
@jamesagnew Do you have time to look at this small PR?

**Comment by abrsystematic** [comment]
@jamesagnew We would like to have this merged. We have to fork Hapi FHIR to build the version of Hapi FHIR we use because of this issue.

**Review by jamesagnew — APPROVED** [review]

**Comment by jamesagnew** [comment]
Apologies for the slow reply- I didn't merge this only because I kept thinking about how we could fix this also for the other versions of FHIR in an organized way but never actually came to a conclusion. I'm going to merge.

**Comment by abrsystematic** [comment]
Understandably :) Thanks.

**Pull request merged**
