### PR TITLE
Adding resource fetcher and assumeValidRestReferences to Validation wrapper

### PR DESCRIPTION
**Pull request by jvitrifork**
Added option for adding resource Fetcher to core validation when using HAPI FHIR validation

### CODE REVIEW

**Comment by grahamegrieve** [comment]
@markiantorno this is what we were discussing this week

**Comment by jvitrifork** [comment]
@jamesagnew unit test added as well as extending the functionality to R4 and R5

**Comment by jvitrifork** [comment]
I've added the latest feature of the validator - meaning that 'assumeValidRestReferences' is now also included. The unit tests only verify that the core stuff is actually invoked properly on the fetcher, and as such the functionality of the core validation mechanism is not verified (the actual business logic of the validator should be contained in the core project, IMHO). As the additions are merely accessor methods, this approach could be sufficient, IMHO.

**Comment by jamesagnew** [comment]
HI @jvitrifork - Would you be able to merge master into this branch just so we can get a clean CI build? We've had some stability issues lately but they appear to be settled down now. Much appreciated.

**Comment by jvitrifork** [comment]
@jamesagnew done

**Comment by jamesagnew** [comment]
Hmm.. This failure appears to be legitimate. I get the same compile failure locally.

Does the org.hl7.fhir.core dependency need to be bumped that far forward? If so, we may need to hold on this until we have this repo synced to the current master of org.hl7.fhir.core (there have been converter changes recently and hapi hasn't caught up yet- hopefully will soon). I'm hoping this could be resolved by just not bumping that dependency though, or bumping it less....

**Comment by jkiddo** [comment]
How far back would you like it?

**Comment by jkiddo** [comment]
Actually, https://github.com/hapifhir/org.hl7.fhir.core/commit/ca29fdf182695b179f1fd522b4eab2efcc5f7b20 shows that it cant go further back as the 'assumeValidRestReferences' is also part of this PR, which is in 4.1.58

**Comment by jamesagnew** [comment]
Changes from this branch have been merged into a working branch `ja_20200205_update_core` which is also accounting for the other structural changes in the latest org.hl7.fhir.core project. 

I am expecting to merge this immediately after the release of HAPI FHIR 4.2.0 on Feb 13.

**Comment by jamesagnew** [comment]
This has now been merged into Master.

**Pull request closed without merging**
